version: "3"
services:
  docker-in-docker:
    image: 'docker:dind'
    container_name: docker-in-docker
    restart: unless-stopped
    privileged: true
    networks: 
        sonarnet:
            aliases: 
                - docker  
    environment:
        - DOCKER_TLS_CERTDIR=/certs
    volumes:
        - jenkins-docker-certs:/certs/client
        - jenkins-data:/var/jenkins_home
    ports:
        - 2376:2376
  jenkins:
    build: 
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    container_name: jenkins
    networks: 
        - sonarnet
    depends_on:
        - nginx
    environment:
        - DOCKER_HOST=tcp://docker:2376
        - DOCKER_CERT_PATH=/certs/client
        - DOCKER_TLS_VERIFY=1
        - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
        - jenkins-data:/var/jenkins_home
        - jenkins-docker-certs:/certs/client:ro
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx2048m
    restart: unless-stopped
    networks: 
        - sonarnet
    depends_on:
        - nginx  
    environment:
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar
        - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube       
        - SONAR_WEB_CONTEXT=/sonar
    volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_logs:/opt/sonarqube/logs
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    networks: 
        - sonarnet
    environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
        - POSTGRES_DB=sonarqube
    volumes:
        - sonarqube_db:/var/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data
  nginx: 
    build: 
        context: .
        dockerfile: nginx-custom.dockerfile
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    networks:
        - sonarnet 
    volumes:
        - nginx_data:/etc/nginx/
        - letsencrypt_data:/etc/letsencrypt/
    ports:
        - 80:80
        - 443:443
        - 9871:9871
        - 9872:9872

volumes:
    postgresql_data:
    sonarqube_bundled-plugins:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_db:
    sonarqube_logs:
    sonarqube_extensions:
    jenkins-docker-certs:
    jenkins-data:
    nginx_data:
    letsencrypt_data:

networks:
    sonarnet:
        driver: bridge
